# Turns files into a C++ source of byte arrays, so that the binary carries them.
#
# Two files ride along: `amberedit.cfg.example`, which `--setup` writes a config
# out of, and `default.tpl`, which it falls back to where no installed copy of
# the template is to be found. Neither can be read off disk at that point —
# the sample config is documentation and the install rules deliberately leave it
# out, and a template is only where a config says it is, which is the file being
# written.
#
# Byte arrays and not configure_file(): the sample holds "@longpid @version" and
# a @-substituting pass has no business anywhere near it. A hex dump has no
# syntax of its own to collide with the content, which a raw string literal does.
#
# Run in script mode from the custom command in the root CMakeLists:
#   cmake -DEXAMPLE_CONFIG=... -DDEFAULT_TEMPLATE=... -DOUTPUT=... -P this

cmake_minimum_required(VERSION 3.16)

function(amberedit_embed path symbol out_var)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "embed_resources: ${path} is not there")
  endif()
  file(READ "${path}" hex HEX)
  string(LENGTH "${hex}" length)
  if(length EQUAL 0)
    message(FATAL_ERROR "embed_resources: ${path} is empty")
  endif()
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
  # Twelve bytes to a line: the generated file is read by a human about once,
  # but one line of 50,000 characters is read by nothing at all. Written out
  # twelve times over because CMake's regex has no bounded repetition.
  string(REGEX REPLACE
         "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
         "\\1\n    " bytes "${bytes}")
  # unsigned char, because a config in UTF-8 holds bytes above 127 and a plain
  # char is signed on every system AmberEdit builds for.
  set(${out_var}
      "const unsigned char ${symbol}[] = {\n    ${bytes}\n};\n"
      PARENT_SCOPE)
endfunction()

amberedit_embed("${EXAMPLE_CONFIG}" kExampleConfig example_array)
amberedit_embed("${DEFAULT_TEMPLATE}" kDefaultTemplate template_array)

file(WRITE "${OUTPUT}"
"// Generated by cmake/embed_resources.cmake — do not edit.
//
// The bytes of amberedit.cfg.example and default.tpl, as the build found them.

#include \"config/embedded_resources.hpp\"

namespace amberedit::config::resources {
namespace {

${example_array}
${template_array}
}  // namespace

std::string_view exampleConfig() {
    return std::string_view(reinterpret_cast<const char*>(kExampleConfig),
                            sizeof(kExampleConfig));
}

std::string_view defaultTemplate() {
    return std::string_view(reinterpret_cast<const char*>(kDefaultTemplate),
                            sizeof(kDefaultTemplate));
}

}  // namespace amberedit::config::resources
")
